FROM node:22-alpine AS builder

WORKDIR /aurora/admin

COPY package*.json ./

RUN npm install

COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build




FROM node:22-alpine AS runnner

WORKDIR /aurora/admin

COPY --from=builder /aurora/admin/.next ./.next

COPY package*.json ./

RUN npm install

EXPOSE 6000

CMD [ "npm", "run", "dev" ]
